; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
debug_init_break = tbreak setup
build_type = debug

[credentials]
wifi_ssids =
	-DSSID1=\"${sysenv.WIFI_SSID}\"
	-DPW1=\"${sysenv.WIFI_PASSWORD}\"
	-DSSID2=\"${sysenv.WIFI_SSID1}\"
	-DPW2=\"${sysenv.WIFI_PASSWORD1}\"
	-DSSID3=\"${sysenv.WIFI_SSID2}\"
	-DPW3=\"${sysenv.WIFI_PASSWORD2}\"
	-DSSID4=\"${sysenv.WIFI_SSID3}\"
	-DPW4=\"${sysenv.WIFI_PASSWORD3}\"
	-DSSID5=\"${sysenv.WIFI_SSID6}\"
	-DPW5=\"${sysenv.WIFI_PASSWORD6}\"
	-DSSID6=\"${sysenv.WIFI_SSID9}\"
	-DPW6=\"${sysenv.WIFI_PASSWORD9}\"

[m5unified]
libs =
    https://github.com/M5Stack/M5Unified.git
    https://github.com/M5Stack/M5GFX.git


[other]
libs =
	https://github.com/mlesniew/PicoMQTT
	https://github.com/mlesniew/PicoWebsocket
	https://github.com/bblanchon/ArduinoJson
	https://github.com/adafruit/Adafruit_VL53L0X.git
	https://github.com/mathertel/OneButton

[common]
flags =
	-O2 -g
	-w
	-DCORE_DEBUG_LEVEL=4
	-DPICOWEBSOCKET_MAX_HTTP_LINE_LENGTH=512
    -DARDUINO_LOOP_STACK_SIZE=16384
    -DHOSTNAME=\"picomqtt\"
    -DMQTT_PORT=1883
    -DMQTTWS_PORT=8883

[env:m5stack-tab5-p4]
board = m5stack-tab5-p4
build_type = debug
board_build.partitions = app3M_spiffs9M_16MB.csv
debug_tool = esp-builtin
debug_init_break = tbreak setup
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
    -Iinclude
    -w
    -DM5UNIFIED
lib_deps =
	${m5unified.libs}
	${other.libs}

[env:m5stack-atoms3]
board = m5stack-atoms3
build_type = debug
debug_tool = esp-builtin
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
    -DM5UNIFIED
	-DBUTTON_PIN=41
lib_deps =
	${m5unified.libs}
	${other.libs}

[env:m5stamp-s3]
board = m5stack-stamps3
debug_tool = esp-builtin
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
    -DM5UNIFIED
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	${m5unified.libs}
	${other.libs}


[env:m5stack-coreS3]
board = m5stack-coreS3
debug_tool = esp-builtin
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
    -DM5UNIFIED
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	${m5unified.libs}
	${other.libs}

[env:m5stack_nanoc6]
board = m5stack_nanoc6
debug_tool = esp-builtin
board_build.partitions = huge_app.csv
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
	-DBUTTON_PIN=9
	-DLED_BLUE=GPIO_NUM_7

lib_deps =
	${other.libs}


;https://www.waveshare.com/esp32-c5-wifi6-kit-n16r4.htm?srsltid=AfmBOoo-skHUZ8L4WezGhntAjR4hWqp2EAgZUN2ILSI46e4bMFcGHqhC
[env:esp32-c5-devkitc1-n16r8]
board = esp32-c5-devkitc1-n16r8
build_type = debug
debug_tool = esp-builtin
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
lib_deps =
	${other.libs}

[env:esp32p4_waveshare_devkit]
board = esp32-p4-evboard
debug_tool = esp-builtin
upload_port = /dev/cu.wchusbserial5AB01728161
board_build.partitions = app3M_spiffs9M_16MB.csv
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
lib_deps =
	${other.libs}

[env:seed_xiao_esp32c6]
board = seeed_xiao_esp32c6
debug_tool = esp-builtin
build_flags =
    ${common.flags}
	${credentials.wifi_ssids}
	-DARDUINO_USB_CDC_ON_BOOT=1
board_build.partitions = huge_app.csv
lib_deps =
	${other.libs}
